name: Release
on:
  push: { tags: 'v[0-9]+.[0-9]+.[0-9]+' }

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - run: npm ci
      - run: npm run -s relnotes | tee relnotes.txt
      # TODO: Port to using gh-cli instead of dedicated action
      - uses: jasonkarns/create-release@9249b73e127bea00eb6f2caa7244657983df0557
        with: { body_path: relnotes.txt }

  homebrew:
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: node-build
        env:
          COMMITTER_TOKEN: ${{ secrets.BOT_TOKEN }}

  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          scope: '@nodenv'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
