name: Generate Definitions
on:
  schedule:
    - cron:  '* */2 * * *' # once every other hour

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run scrape-definitions
