name: Generate Definitions
on:
  - schedule: [{ cron:  '0 */4 * * *' }] # every 4 hrs: https://crontab.guru/#0_*/4_*_*_*
  - workflow_dispatch
  - push

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run scrape-definitions
    - run: npm run commit-definitions
      env:
        GIT_AUTHOR_NAME: 'nodenv bot'
        GIT_AUTHOR_EMAIL: 'jason.karns+nodenv@gmail.com'
        GIT_COMMITTER_NAME: 'nodenv bot'
        GIT_COMMITTER_EMAIL: 'jason.karns+nodenv@gmail.com'

    - id: scraped
      name: git log
      run: |
        msg=$(git log master.. --format='- %s')
        echo "::set-output name=nodes::${msg//$'\n'/'%0A'}"
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.BOT_TOKEN }}
        branch: latest-scraped-definitions
        title: 'Scraped latest definitions'
        body: ${{ steps.scraped.outputs.nodes }}
