name: Generate Definitions
on:
  schedule:
    - cron:  '0 */4 * * *' # every 4 hrs

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run scrape-definitions
