name: Generate Definitions
on: push
  # schedule: [{ cron:  '0 */4 * * *' }] # every 4 hrs: https://crontab.guru/#0_*/4_*_*_*

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run scrape-definitions
    - id: scraped
      name: Commit new definitions
      run: |
        git config user.name 'nodenv actions [bot]'
        git config user.email 'noreply@github.com'
        nodes=$(git ls-files --others --exclude-standard -- share/node-build |
            while read -r node_def; do
              node_name=${node_def##*/}
              git add "$node_def"
              git commit -m "$node_name" -m 'Created with `npm run submit-definitions`.'
              echo "- $node_name"
            done)
        echo "::set-output name=nodes::${nodes//$'\n'/'%0A'}"
    - uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
        branch: latest-scraped-definitions-testing
        title: 'Scraped latest node definitions'
        body: ${{ steps.scraped.outputs.nodes }}
