name: Test
on:
  pull_request:
  push: {branches: main}
  schedule: [{cron: '0 0 10 * *'}] # monthly https://crontab.guru/#0_0_10_*_*
  workflow_dispatch:
permissions: {contents: read}

jobs:
  test:
    uses: nodenv/.github/.github/workflows/test.yml@v4
    with: {superlinter: false} # TODO renable superlinter
    permissions:
      contents: read
      packages: read
      id-token: write
      security-events: write
      statuses: write

  # https://github.com/redhat-plumbers-in-action/differential-shellcheck
  shellcheck:
    permissions: {contents: read, security-events: write}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with: {fetch-depth: 0}
    - uses: redhat-plumbers-in-action/differential-shellcheck@b8c7b83d16cce15d13563f5d055b34b9e3360ed3 # v5.3.1
      with:
        severity: error # TODO strengthen
        token: ${{ secrets.GITHUB_TOKEN }}

  lts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
    - run: npm ci
    - run: npm run lint:lts

  checksums:
    runs-on: ubuntu-latest
    steps:
      # FIXME workaround https://github.com/actions/checkout/issues/910
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      with: { fetch-depth: 0 }
    - run: npm ci
    - if: github.event_name == 'pull_request'
      run: npm run lint:checksums -- origin/${{github.base_ref}}
    - run: npm run lint:checksums -- HEAD^
      if: github.event_name == 'push'
