name: Test
on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macOS]

    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm test
