name: Test
on:
  pull_request:
  push: { branches: main }

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy: { matrix: { os: [ubuntu, macOS] }}
    steps:
    - uses: actions/checkout@v4
    - run: npm cit

  lts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run lint:lts

  checksums:
    runs-on: ubuntu-latest
    steps:
      # FIXME workaround https://github.com/actions/checkout/issues/910
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - run: npm ci
    - if: github.event_name == 'pull_request'
      run: npm run lint:checksums -- origin/${{github.base_ref}}
    - run: npm run lint:checksums -- HEAD^
      if: github.event_name == 'push'
