name: Verify Definitions
on:
  pull_request:
    paths:
    - 'share/node-build/**'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run verify-definitions -- origin/${{github.base_ref}}
