name: Version Bump
on:
  schedule: [{ cron: '0 10 * * *' }] # daily: https://crontab.guru/#0_10_*_*_*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}

      - run: |-
          npm run preversion --silent -- -o -v -- share/node-build || status=$?
          case "${status:-0}" in
            0) echo "release=true" >> $GITHUB_ENV;;
            1) exit 0;; # exit successfully to mask error, but don't release
            *) exit $status ;; # all other error codes are true failures
          esac

      - if: ${{ env.release }}
        run: npm version patch
        env:
          GIT_AUTHOR_NAME: ${{ vars.NODENV_BOT_NAME }}
          GIT_AUTHOR_EMAIL: ${{ vars.NODENV_BOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ vars.GHA_BOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ vars.GHA_BOT_EMAIL }}
